---
- hosts: [ server ]
  remote_user: "{{ remote_user }}"
  become: yes

  tasks:
    - yum: pkg={{item}} state=present
      with_items:
        - net-tools
        - fail2ban-systemd
        - yum-cron
        - scponly
        - nfs-utils

    - copy: src=fail2ban-jail.local dest=/etc/fail2ban/jail.local
      notify:
        - restart fail2ban

    - service: name={{item}} state=started enabled=yes
      with_items:
        - fail2ban
        - yum-cron

    - file: path={{data_mount}}/{{remote_user}} state=directory owner={{remote_user}}

    - name: Android backup android-sync user
      user:
        name: android-sync
        shell: /bin/bash
        password: "!"
        createhome: yes

    - name: Android backup directory
      file: path={{data_mount}}/oandbackups state=directory owner=android-sync

    - file: path=/srv/nfs/Lataukset state=directory

    - name: Mount home server
      mount:
        path: /srv/nfs/Lataukset
        fstype: nfs
        state: present # or mounted
        src: "{{nfs_host}}:/export/Lataukset"

  handlers:
    - name: restart fail2ban
      service: name=fail2ban state=restarted
